### ISSUE TITLE
testcase getting failed with resource not found error 

### ISSUE THREAD

**Issue by gundun** [airlift/testing-mysql-server#3]
Hi,

below are the full logs for test case failure, could you please help me out to fix these error.

~/testing-mysql-server# mvn clean install

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building testing-mysql-server 0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testing-mysql-server ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (default) @ testing-mysql-server ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ testing-mysql-server ---
[INFO]
[INFO] --- maven-dependency-versions-check-plugin:2.0.2:check (default) @ testing-mysql-server ---
[INFO] Checking dependency versions
[INFO]
[INFO] --- license-maven-plugin:2.3:check (default) @ testing-mysql-server ---
[INFO] Checking licenses...
[INFO]
[INFO] --- jacoco-maven-plugin:0.6.2.201302030002:prepare-agent (default) @ testing-mysql-server ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.6.2.201302030002/org.jacoco.agent-0.6.2.201302030002-runtime.jar=destfile=/root/testing-mysql-server/target/jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testing-mysql-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/testing-mysql-server/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ testing-mysql-server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /root/testing-mysql-server/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testing-mysql-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/testing-mysql-server/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ testing-mysql-server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /root/testing-mysql-server/target/test-classes
[INFO]
[INFO] --- maven-dependency-plugin:2.8:analyze-only (default) @ testing-mysql-server ---
[INFO] No dependency problems found
[INFO]
[INFO] --- maven-dependency-plugin:2.8:analyze-duplicate (default) @ testing-mysql-server ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO]
[INFO] --- maven-dependency-plugin:2.8:analyze-dep-mgt (default) @ testing-mysql-server ---
[INFO] Found Resolved Dependency / DependencyManagement mismatches:
[INFO]  Ignoring Direct Dependencies.
[INFO]    None
[INFO]
[INFO] --- maven-duplicate-finder-plugin:1.0.6:check (default) @ testing-mysql-server ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[INFO]
[INFO] --- maven-surefire-plugin:2.14:test (default-test) @ testing-mysql-server ---
[INFO] Surefire report directory: /root/testing-mysql-server/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.airlift.testing.mysql.TestTestingMySqlServer
Configuring TestNG with: TestNG652Configurator
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.797 sec <<< FAILURE!
testDatabase(io.airlift.testing.mysql.TestTestingMySqlServer)  Time elapsed: 0.43 sec  <<< FAILURE!
java.util.MissingResourceException: Resource '5-5-9/Linux-ppc64le/mysqld' not found
        at com.mysql.management.util.Streams.getResourceAsStream(Streams.java:124)
        at com.mysql.management.util.Streams.getResourceAsStream(Streams.java:108)
        at com.mysql.management.util.Streams$1.inner(Streams.java:140)
        at com.mysql.management.util.Exceptions$VoidBlock.exec(Exceptions.java:129)
        at com.mysql.management.util.Streams.createFileFromResource(Streams.java:153)
        at com.mysql.management.MysqldResource.extractExecutable(MysqldResource.java:544)
        at com.mysql.management.MysqldResource.makeMysqld(MysqldResource.java:532)
        at com.mysql.management.MysqldResource.deployFiles(MysqldResource.java:515)
        at com.mysql.management.MysqldResource.exec(MysqldResource.java:492)
        at com.mysql.management.MysqldResource.start(MysqldResource.java:213)
        at com.mysql.management.MysqldResource.start(MysqldResource.java:168)
        at io.airlift.testing.mysql.TestingMySqlServer.<init>(TestingMySqlServer.java:78)
        at io.airlift.testing.mysql.TestingMySqlServer.<init>(TestingMySqlServer.java:56)
        at io.airlift.testing.mysql.TestTestingMySqlServer.testDatabase(TestTestingMySqlServer.java:35)

Results :

Failed tests:
  TestTestingMySqlServer.testDatabase:35 » MissingResource Resource '5-5-9/Linux...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.434 s
[INFO] Finished at: 2015-12-17T19:12:50+05:30
[INFO] Final Memory: 17M/41M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project testing-mysql-server: There are test failures.
[ERROR]
[ERROR] Please refer to /root/testing-mysql-server/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by electrum** [comment]
This is because MySQL MXJ does not have binaries for ppc64le. Unfortunately, MXJ has been discontinued, the chance of it getting upgraded is likely zero. Though, we might be able to add the binary ourselves as a resource.

Unfortunately, MySQL doesn't have any prebuilt binaries for that platform: http://dev.mysql.com/downloads/mysql/

I suggest filing an issue and asking them to support it for future releases.

**Comment by gundun** [comment]
Thanks electrum for taking your time to help me and appreciate your patience.
