### ISSUE TITLE
NullPointerException on shutdown

### ISSUE THREAD

**Issue by electrum** [airlift/testing-mysql-server#5]
```
java.lang.RuntimeException: java.lang.NullPointerException
    at com.mysql.management.MysqldResource.destroyShell(MysqldResource.java:359)
    at com.mysql.management.MysqldResource.shutdown(MysqldResource.java:323)
    at io.airlift.testing.mysql.TestingMySqlServer.close(TestingMySqlServer.java:136)
    at io.airlift.testing.Closeables.closeAllRuntimeException(Closeables.java:76)
    at com.facebook.presto.raptor.TestRaptorIntegrationSmokeTestMySql.destroy(TestRaptorIntegrationSmokeTestMySql.java:54)
```

**Comment by electrum** [comment]
This is a race condition caused by the completion listener doing `setShell(null)` in another thread while the `shutdown()` method is running.

We could fix this with reflection by grabbing `shell` from `MysqldResource`, casting to `Shell.Default`, then grabbing `listeners` and clearing it.

**Comment by electrum** [comment]
This was fixed with the removal of MXJ.
