### ISSUE TITLE
Failure on building testing-mysql-server

### ISSUE THREAD

**Issue by ArchaB** [airlift/testing-mysql-server#7]
Tried to clone and build testing-mysql-server. 

Steps followed:
  **git clone https://github.com/airlift/testing-mysql-server
  mvn clean install -DskipTests**

Build failed with the following error
**[DEBUG] Findbugs arg is /testing-mysql-server/target/classes
     [java] The following errors occurred during analysis:
     [java] Nov 14, 2016 12:25:36 PM edu.umd.cs.findbugs.TextUIBugReporter reportAnalysisError
     [java] SEVERE: Unable to get XClass for java/lang/StringBuilder
     [java] java.lang.ArrayIndexOutOfBoundsException: 20993
     [java]     at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:554)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:266)
     [java]     at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]     at edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1227)
     [java]     at edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1200)
     [java]     at edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]     at edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]     at edu.umd.cs.findbugs.ba.AnalysisCacheToAnalysisContextAdapter.setAppClassList(AnalysisCacheToAnalysisContextAdapter.java:400)
     [java]     at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:982)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:391)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1300)
     [java]   Unable to get XClass for java/lang/StringBuilder**

**Comment by ArchaB** [comment]
Gentle reminder
